version: 2
jobs:
  test:
    working_directory: /home/circleci/actions
    docker:
      - image: rayriffy/yarn:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Update Alpine
          command: |
            apk update
      - run:
          name: Test file
          command: |
            yarn
            yarn test
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: rayriffy/yarn:latest
    working_directory: /home/circleci/actions
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Update Alpine
          command: |
            apk update
      - run:
          name: Build file
          command: |
            yarn
            yarn build
      - save_cache:
          key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - release